import type { AppData } from "./types";

const now = "2026-05-07T00:00:00.000Z";

export const sampleData: AppData = {
  ingredients: [
    {
      id: "ing-flour",
      name: "薄力粉",
      category: "粉類",
      supplier: "東京製粉",
      packageName: "業務用 25kg",
      packageAmountGram: 25000,
      packageUnit: "g",
      gramPerUnit: 1,
      price: 5200,
      taxType: "税抜",
      caloriesPer100g: 349,
      proteinPer100g: 8.3,
      fatPer100g: 1.5,
      carbsPer100g: 75.8,
      saltPer100g: 0,
      allergens: ["小麦"],
      otherAllergen: "",
      labelName: "小麦粉",
      memo: "スポンジ用",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ing-sugar",
      name: "砂糖",
      category: "糖類",
      supplier: "東京製糖",
      packageName: "グラニュー糖 30kg",
      packageAmountGram: 30000,
      packageUnit: "g",
      gramPerUnit: 1,
      price: 6100,
      taxType: "税抜",
      caloriesPer100g: 391,
      proteinPer100g: 0,
      fatPer100g: 0,
      carbsPer100g: 100,
      saltPer100g: 0,
      allergens: [],
      otherAllergen: "",
      labelName: "砂糖",
      memo: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ing-egg",
      name: "全卵",
      category: "卵",
      supplier: "山手鶏卵",
      packageName: "液卵 1kg",
      packageAmountGram: 1000,
      packageUnit: "g",
      gramPerUnit: 1,
      price: 530,
      taxType: "税込",
      caloriesPer100g: 142,
      proteinPer100g: 12.2,
      fatPer100g: 10.2,
      carbsPer100g: 0.4,
      saltPer100g: 0.36,
      allergens: ["卵"],
      otherAllergen: "",
      labelName: "卵",
      memo: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ing-butter",
      name: "無塩バター",
      category: "乳製品",
      supplier: "北海乳業",
      packageName: "450g",
      packageAmountGram: 450,
      packageUnit: "g",
      gramPerUnit: 1,
      price: 980,
      taxType: "税込",
      caloriesPer100g: 720,
      proteinPer100g: 0.5,
      fatPer100g: 83,
      carbsPer100g: 0.2,
      saltPer100g: 0.02,
      allergens: ["乳"],
      otherAllergen: "",
      labelName: "バター",
      memo: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ing-cream",
      name: "生クリーム",
      category: "乳製品",
      supplier: "山手デイリー",
      packageName: "乳脂肪42% 1L",
      packageAmountGram: 1000,
      packageUnit: "g",
      gramPerUnit: 1,
      price: 760,
      taxType: "税込",
      caloriesPer100g: 433,
      proteinPer100g: 2,
      fatPer100g: 45,
      carbsPer100g: 3.1,
      saltPer100g: 0.08,
      allergens: ["乳"],
      otherAllergen: "",
      labelName: "クリーム",
      memo: "乳成分を含む",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ing-strawberry",
      name: "苺",
      category: "果物",
      supplier: "青果市場",
      packageName: "1パック 300g",
      packageAmountGram: 300,
      packageUnit: "g",
      gramPerUnit: 1,
      price: 680,
      taxType: "税込",
      caloriesPer100g: 31,
      proteinPer100g: 0.9,
      fatPer100g: 0.1,
      carbsPer100g: 8.5,
      saltPer100g: 0,
      allergens: [],
      otherAllergen: "",
      labelName: "苺",
      memo: "季節で価格変動あり",
      createdAt: now,
      updatedAt: now,
    },
  ],
  products: [
    {
      id: "prd-shortcake",
      name: "苺のショートケーキ",
      isIntermediateMaterial: false,
      sellingPrice: 620,
      taxType: "税込",
      targetCostRate: 32,
      displayUnit: "1個あたり",
      yieldCount: 8,
      beforeBakeWeightGram: 1040,
      afterBakeWeightGram: 960,
      weightPerPieceGram: 120,
      memo: "8個取りのサンプルレシピ",
      createdAt: now,
      updatedAt: now,
    },
  ],
  recipeItems: [
    { id: "rec-flour", productId: "prd-shortcake", ingredientId: "ing-flour", itemType: "ingredient", intermediateProductId: "", usageType: "gram", amountGram: 120, baseAmountGram: 120, usedCount: 1, totalCount: 1, fractionDenominator: 1, createdAt: now, updatedAt: now },
    { id: "rec-sugar", productId: "prd-shortcake", ingredientId: "ing-sugar", itemType: "ingredient", intermediateProductId: "", usageType: "gram", amountGram: 140, baseAmountGram: 140, usedCount: 1, totalCount: 1, fractionDenominator: 1, createdAt: now, updatedAt: now },
    { id: "rec-egg", productId: "prd-shortcake", ingredientId: "ing-egg", itemType: "ingredient", intermediateProductId: "", usageType: "gram", amountGram: 280, baseAmountGram: 280, usedCount: 1, totalCount: 1, fractionDenominator: 1, createdAt: now, updatedAt: now },
    { id: "rec-butter", productId: "prd-shortcake", ingredientId: "ing-butter", itemType: "ingredient", intermediateProductId: "", usageType: "gram", amountGram: 45, baseAmountGram: 45, usedCount: 1, totalCount: 1, fractionDenominator: 1, createdAt: now, updatedAt: now },
    { id: "rec-cream", productId: "prd-shortcake", ingredientId: "ing-cream", itemType: "ingredient", intermediateProductId: "", usageType: "gram", amountGram: 330, baseAmountGram: 330, usedCount: 1, totalCount: 1, fractionDenominator: 1, createdAt: now, updatedAt: now },
    { id: "rec-strawberry", productId: "prd-shortcake", ingredientId: "ing-strawberry", itemType: "ingredient", intermediateProductId: "", usageType: "gram", amountGram: 240, baseAmountGram: 240, usedCount: 1, totalCount: 1, fractionDenominator: 1, createdAt: now, updatedAt: now },
  ],
  priceHistories: [
    {
      id: "hist-cream",
      ingredientId: "ing-cream",
      oldPrice: 720,
      newPrice: 760,
      changedAt: now,
      memo: "サンプル価格改定",
    },
  ],
  ingredientAliases: [],
};
